/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export interface MousePosition {
  x: number
  y: number
}
export function getMousePosition(): MousePosition
